'use strict';
var mongoose = require('mongoose');
mongoose.Promise = global.Promise;
var Schema = mongoose.Schema;

  var schapplicant = new Schema({
    APPLICANT_FIRST_NAME: {type: String,required: true},
    APPLICANT_MIDDLE_NAME : {type: String},
    APPLICANT_LAST_NAME : {type: String, required: true},
    APPLICANT_GENDER : {type: String},
    APPLICANT_RACE: {type: String},
    APPLICANT_ADDRESS: [
      {
          APPLICANT_ADDRESS1_STREET:{ type: String },
          APPLICANT_ADDRESS2_APT:{ type: String },
          APPLICANT_ADDRESS3_CITY:{ type: String},
          APPLICANT_ADDRESS4_STATE:{ type: String},
          APPLICANT_ADDRESS5_ZIP: {type: String},
          APPLICANT_ADDRESS6_COUNTRY: {type: String}
       }],
    APPLICANT_DAY_PHONE:
    APPLICANT_EVENING_PHONE:
    APPLICANT_EMAIL:
    APPLICANT_VISA_TYPE:
    APPLICANT_MARITAL_STATUS:
    APPLICANT_EDUCATION:
APPLICANT_PARENT_NAME:
APPLICANT_CITIZENSHIP:
APPLICANT_DATE_OF_BIRTH:
APPLICANT_PLACE_OF_BIRTH:
APPLICANT_SSN:
APPLICANT_SPOUSE_NAME:
APPLICANT_SPOUSE_EDUCATION:
APPLICANT_NUMBER_OF_CHILDREN:
APPLICANT_EMPLOYER:
APPLICANT_REUIMBURSEMENT_OPTION_YORN:
APPLIVANT_VETERAN_STATUS_YORN:
APPLICANT_VETERAN_BRANCH:
APPLICANT_VETERAN_DISCHARGE_TYPE:
APPLICANT_VETERAN_DISCHARGE_DATE:
APPLICANT_HEALTH_CONDITION:
APPLICANT_HAIR_COLOR:
APPLICANT_EYE_COLOR:
APPLICANT_WEIGHT:
APPLICANT_HEIGHT:
APPLICANT_VISION:
APPLIVANT_CORRECTED_VISION:







  });
module.exports = mongoose.model('tbl_applicant', schapplicant);
